version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
  pre_build: # commands to be run before build
    commands:
    - echo Logging in to Amazon ECR....
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
    - echo Building the Docker image...
    - printf '[{"name":"$IMAGE_REPOSITORY_NAME","imageUri":"$ECR_URI/$IMAGE_REPOSITORY_NAME:$IMAGE_TAG"}]' > imagedefinitions.json
    - docker-compose build
    - docker tag $IMAGE_REPOSITORY_NAME:$IMAGE_TAG $ECR_URI/$IMAGE_REPOSITORY_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $ECR_URI/$IMAGE_REPOSITORY_NAME:$IMAGE_TAG
artifacts:
  type: zip
  files:
    - '**/*'
  name: php-modern-demo-art-$(date +%Y-%m-%d)
