services:
    php:
        image: php-modern-demo:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        environment:
            OP_CACHE: true
            SSL_MODE: "mixed"
            AUTORUN_ENABLED: true
            AUTORUN_LARAVEL_MIGRATION: true
